stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data_preparation.py
    deps:
    - data/raw
    - src/data_preparation.py
    outs:
    - data/processed
