stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - src/data/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_preparation:
    cmd: python src/data/data_preparation.py
    deps:
    - data/raw
    - src/data/data_preparation.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed
    - src/model/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    outs:
    - reports/run_info.json
    metrics:
    - reports/metrics.json
  model_registration:
    cmd: python src/model/model_registration.py
    deps:
    - reports/run_info.json
    - src/model/model_registration.py
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step